index:
    path:       /{utc}
    controller: App\Controller\ApiController::getTime
    methods:    GET
    requirements:
        utc: .+
    defaults:
        {
            utc: now
            _format: json
        }

